const tempPlayList = [
  {
    id: 1,
    name: 'Chase',
    author: 'Alexander Nakarada',
    release_date: '2005-06-11',
    genre: 'Классическая музыка',
    duration_in_seconds: 205,
    album: 'Chase',
    logo: null,
    track_file:
      'https://painassasin.online/media/music_files/Alexander_Nakarada_-_Chase.mp3',
    stared_user: [],
  },
  {
    id: 2,
    name: 'Guilt',
    author: 'Nero',
    release_date: '2006-06-11',
    genre: 'Rap',
    duration_in_seconds: 205,
    album: 'Welcome Reality',
    logo: null,
    track_file:
      'https://painassasin.online/media/music_files/Alexander_Nakarada_-_Chase.mp3',
    stared_user: [],
  },
  {
    id: 3,
    name: 'Elektro',
    author: 'Dynoro, Outwork, Mr. Gee',
    release_date: '2015-06-11',
    genre: 'Texno',
    duration_in_seconds: 305,
    album: 'Elektro',
    logo: null,
    track_file:
      'https://painassasin.online/media/music_files/Alexander_Nakarada_-_Chase.mp3',
    stared_user: [],
  },
  {
    id: 4,
    name: 'I’m Fire',
    author: 'Ali Bakgor',
    release_date: '1812-06-11',
    genre: 'Big beat',
    duration_in_seconds: 205,
    album: 'I’m Fire',
    logo: null,
    track_file:
      'https://painassasin.online/media/music_files/Alexander_Nakarada_-_Chase.mp3',
    stared_user: [],
  },
  {
    id: 5,
    name: 'Non Stop',
    author: 'Стоункат, Psychopath',
    release_date: '2023-06-11',
    genre: 'Burda',
    duration_in_seconds: 105,
    album: 'Non Stop',
    logo: null,
    track_file:
      'https://painassasin.online/media/music_files/Alexander_Nakarada_-_Chase.mp3',
    stared_user: [],
  },
  {
    id: 6,
    name: 'Run Run',
    author: 'Jaded, Will Clarke, AR/CO',
    release_date: '2019-06-11',
    genre: 'Jazz',
    duration_in_seconds: 259,
    album: 'Run Run',
    logo: null,
    track_file:
      'https://painassasin.online/media/music_files/Alexander_Nakarada_-_Chase.mp3',
    stared_user: [],
  },
  {
    id: 7,
    name: 'Eyes on Fire',
    author: 'Blue Foundation, Zeds Dead',
    release_date: '2019-06-11',
    genre: 'Jazz',
    duration_in_seconds: 345,
    album: 'Eyes on Fire',
    logo: null,
    track_file:
      'https://painassasin.online/media/music_files/Alexander_Nakarada_-_Chase.mp3',
    stared_user: [],
  },
]

export default tempPlayList
